// Render the approved full-bleed PCB thermal artwork into platform icon sizes.
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const require = createRequire(import.meta.url);
let sharp;
try { sharp = require('sharp'); }
catch { sharp = require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES, 'sharp')); }
const target = path.resolve('public/icons');
await mkdir(target,{recursive:true});
const master = path.join(target, 'pcb-thermal-master-v3.png');
for(const [name,size] of [['pcb-apple-v3.png',180],['pcb-192-v3.png',192],['pcb-512-v3.png',512],['pcb-maskable-v3.png',512]]) {
  await sharp(master).resize(size,size,{fit:'cover'}).flatten({background:'#08206c'}).png().toFile(path.join(target,name));
}
const apple = await readFile(path.join(target, 'pcb-apple-v3.png'));
await writeFile('public/apple-touch-icon.png', apple);
await writeFile('public/apple-touch-icon-precomposed.png', apple);
const dataURL = async (name) => `data:image/png;base64,${(await readFile(path.join(target, name))).toString('base64')}`;
// Embedded image bytes need no separate, potentially unauthenticated icon request.
await writeFile('lib/app-icons.ts', `// Generated by scripts/create-icons.mjs. Contains only PNG image bytes.\nexport const APPLE_ICON_DATA_URL = ${JSON.stringify(await dataURL('pcb-apple-v3.png'))};\nexport const APP_ICON_DATA_URL = ${JSON.stringify(await dataURL('pcb-192-v3.png'))};\n`);
const manifest = {
  id: '/', name: 'pcb-k計算', short_name: 'pcb-k計算',
  description: '逐層計算 PCB 的板面及厚度方向導熱係數。', lang: 'zh-Hant',
  start_url: '/pcb-k?source=homescreen', scope: '/', display: 'standalone', orientation: 'any',
  background_color: '#f5f3ed', theme_color: '#164c3a',
  prefer_related_applications: false, categories: ['productivity', 'utilities'],
  icons: [
    { src: 'icons/pcb-192-v3.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icons/pcb-512-v3.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icons/pcb-maskable-v3.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
for (const name of ['manifest.webmanifest', 'pcb-k.webmanifest']) {
  await writeFile(path.join('public', name), JSON.stringify(manifest, null, 2) + '\n');
}
console.log('Full-bleed PCB thermal PNGs, embedded icons and pcb-k計算 manifests generated.');
