// Render a code-native SVG wordmark; the PNGs are checked into source.
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const require = createRequire(import.meta.url);
let sharp;
try { sharp = require('sharp'); }
catch { sharp = require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES, 'sharp')); }
const target = path.resolve('public/icons');
await mkdir(target,{recursive:true});
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
<rect width="512" height="512" fill="#164c3a"/>
<text x="256" y="316" text-anchor="middle" fill="#fffdf5" font-family="DejaVu Sans,Arial,sans-serif" font-weight="bold" font-size="176" letter-spacing="-5">PCB</text>
</svg>`;
await writeFile(path.join(target,'pcb-icon.svg'),svg);
for(const [name,size] of [['pcb-apple-v2.png',180],['pcb-192-v2.png',192],['pcb-512-v2.png',512],['pcb-maskable-v2.png',512]]) {
  await sharp(Buffer.from(svg)).resize(size,size).flatten({background:'#164c3a'}).png().toFile(path.join(target,name));
}
const apple = await readFile(path.join(target, 'pcb-apple-v2.png'));
await writeFile('public/apple-touch-icon.png', apple);
await writeFile('public/apple-touch-icon-precomposed.png', apple);
const dataURL = async (name) => `data:image/png;base64,${(await readFile(path.join(target, name))).toString('base64')}`;
// Embedded image bytes need no separate, potentially unauthenticated icon request.
await writeFile('lib/app-icons.ts', `// Generated by scripts/create-icons.mjs. Contains only PNG image bytes.\nexport const APPLE_ICON_DATA_URL = ${JSON.stringify(await dataURL('pcb-apple-v2.png'))};\nexport const APP_ICON_DATA_URL = ${JSON.stringify(await dataURL('pcb-192-v2.png'))};\n`);
const manifest = {
  id: '/', name: 'pcb-k計算', short_name: 'pcb-k計算',
  description: '逐層計算 PCB 的板面及厚度方向導熱係數。', lang: 'zh-Hant',
  start_url: '/pcb-k?source=homescreen', scope: '/', display: 'standalone', orientation: 'any',
  background_color: '#f5f3ed', theme_color: '#164c3a',
  prefer_related_applications: false, categories: ['productivity', 'utilities'],
  icons: [
    { src: await dataURL('pcb-192-v2.png'), sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: await dataURL('pcb-512-v2.png'), sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: await dataURL('pcb-maskable-v2.png'), sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
for (const name of ['manifest.webmanifest', 'pcb-k.webmanifest']) {
  await writeFile(path.join('public', name), JSON.stringify(manifest, null, 2) + '\n');
}
console.log('PCB wordmark PNGs, embedded icons and pcb-k計算 manifests generated.');
